#######################################################################################################
# docker-compose.yml
#
#   Setup the docker containers that make up the media server
#
#
#   When configuring the containerized applications use the service name when a host ip is called for
#
#   mam - 12/1/2020 everything works except the TV detecting the server
#
#######################################################################################################


version: "3.7"
services:
# Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer-ce
    hostname: portainer
    container_name: portainer
    restart: always
    networks:
      - ms_net
    volumes:
      - ${USERDIR}/docker/portainer:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    ports:
      - 9000:9000
      - 8000:8000
    command: -H unix:///var/run/docker.sock
    environment:
      - TZ=${TZ}
# Watchtower - Automatic Update of Containers/Apps
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    hostname: watchtower
    restart: always
    networks:
      - ms_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/shared:/shared
    command: --schedule "0 0 4 * * *" --cleanup
    # command: --interval 30 --cleanup
# transmission - torrent engine
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    networks:
      - ms_net
    volumes:
      - ${USERDIR}/docker/transmission:/config
      - /media/BlackHole/torrent_downloads:/downloads
      - ${USERDIR}/docker/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped 
# Sonarr – TV Show Download and Management
  sonarr:
    image: linuxserver/sonarr
    hostname: sonarr
    container_name: sonarr
    restart: always
    networks:
      - ms_net
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - /media/BlackHole/torrent_downloads:/downloads
      - /media/Video/TV Shows/:/tv
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    ports:
      - 8989:8989      
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
# Radarr – Movie Download and Management
  radarr:
    image: linuxserver/radarr
    hostname: radarr
    container_name: radarr
    restart: always
    networks:
      - ms_net
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - /media/BlackHole/torrent_downloads:/downloads
      - /media/Video/Movies:/movies
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
# Jackett – Torrent Proxy
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    hostname: jackett
    restart: always
    networks:
      - ms_net
    volumes:
      - ${USERDIR}/docker/jackett:/config
      - /media/BlackHole/torrent_downloads/complete:/downloads
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}      
# Plex Media Server
  plex_dev_3.0:
    image: linuxserver/plex:latest
    container_name: plex_dev_3.0
    hostname: plex_dev_3.0
    restart: always
    networks:
      - ms_net
    volumes:
      - ${USERDIR}/docker/plex_dev_3.0:/config
      - ${USERDIR}/docker/downloads/plex_tmp:/transcode
      - ${USERDIR}/docker/shared:/shared
      # - ${USERDIR}:/data
      - /media/Video/TV Shows/:/tv
      - /media/Video/Movies/:/movies
      - /media/BlackHole/music/KEB_Music_1/:/music1
      - /media/BlackHole/music/KEB_Music_2/:/music2
      - ${USERDIR}//ImageLib/:/pics
    ports:
      - 32400:32400/tcp
    environment:
      - TZ=${TZ}
      - HOSTNAME=plex_dev_3.0
      - PLEX_CLAIM=claim-LzRF8xoxsc38pLzLdaVY
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - PUID=${PUID}
      - PGID=${PGID}
      - ADVERTISE_IP=http://192.168.132.200:32400
networks:
  ms_net:

#

